### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by EdenJohnson2006** [AFXR17light/memory#1]
如果我没记错的话，最早这个repo是没有Issues的。
受这个Repo影响，我的Thinking也没有开放Issues...
今天手机变成了亮砖头，所以来看看这个Repo。
开放了Issues？
...
所以，是为了什么而开的呢？

**Comment by AFXR17light** [comment]
这还算是一个安静的地方，能来到这里的人很少。
当时我只是无心地打开了issues，相当于一个评论区……说不定会有人留下足迹呢？
开与不开似乎都没什么区别，那不如先开着吧。

**Comment by AFXR17light** [comment]
> 如果我没记错的话，最早这个repo是没有Issues的。
> 受这个Repo影响，我的Thinking也没有开放Issues...
> 今天手机变成了亮砖头，所以来看看这个Repo。
> 开放了Issues？
> ...
> 所以，是为了什么而开的呢？

这还算是一个安静的地方，能来到这里的人很少。
当时我只是无心地打开了issues，相当于一个评论区……说不定会有人留下足迹呢？
开与不开似乎都没什么区别，那不如先开着吧。

**Comment by EdenJohnson2006** [comment]
> > 如果我没记错的话，最早这个repo是没有Issues的。
> > 受这个Repo影响，我的Thinking也没有开放Issues...
> > 今天手机变成了亮砖头，所以来看看这个Repo。
> > 开放了Issues？
> > ...
> > 所以，是为了什么而开的呢？
> 
> 这还算是一个安静的地方，能来到这里的人很少。
> 当时我只是无心地打开了issues，相当于一个评论区……说不定会有人留下足迹呢？
> 开与不开似乎都没什么区别，那不如先开着吧。

如此...这个似乎还行...不知道会不会有所改变的说。

**Comment by YINZHI-keji** [comment]
说不定真有人会留下足迹。
